config/routes.rb
Rails.application.routes.draw do


  get 'realisations/destroy'
  resources :realisations do
  end

  get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'bio', to: 'pages#bio'
  get 'approche', to: 'pages#approche'
  get 'prestations', to: 'pages#prestations'
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/realisation.rb
class Realisation < ApplicationRecord
  has_many_attached :photos
  validates :name, presence: true
  validates :category, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def approche
  end

  def prestations
  end

  def bio
  end

  def contact
  end

end

app/controllers/realisations_controller.rb
class RealisationsController < ApplicationController
  before_action :find_realisation, only: [:show, :edit, :update, :destroy]

  # GET /realisations
  def index
    @realisations = Realisation.all
  end

  # GET /realisations/new
  def show
    @realisation = Realisation.find(params[:id])
  end

  # GET /realisations/1
  def new
    @realisation = Realisation.new
  end

  # GET /realisations/1/edit
  def edit
  end

  # POST /realisations/
  def create
    @realisation = Realisation.new(realisation_params)
    if @realisation.save
      redirect_to @realisation, notice: "Realisation was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /realisations/1
  def update
    if @realisation.update(realisation_params)
      redirect_to @realisation, notice: "Realisation was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /realisations/1
  def destroy
    @realisation.destroy
    redirect_to realisations_path, notice: 'Realisation was successfully destroyed.'
  end

  private

  # Callbacks to share common steup or constraints between actions
  def find_realisation
    @realisation = Realisation.find(params[:id])
  end

  # Only allow a trusted parameter "white list" approach
  def realisation_params
    params.require(:realisation).permit(:name, :category, :description, photos: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

   <!--  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> -->
  </body>
</html>

app/views/pages/approche.html.erb
<div class="banner2" w-100 >
  <%= image_tag "greenlamp3.jpg", class: "bannerpicture" %>
</div>

app/views/pages/bio.html.erb
<%= content_for(:navbar_class, "navbar_home") %>


<div class="banner2" w-100 >
  <%= image_tag "greenlamp3.jpg", class: "bannerpicture" %>
</div>

<div class="container">
  <div class="photo d-flex justify-content-center align-items-center">
    <%= image_tag("Fanny.jpeg", size: "200x200", class: "rounded-circle")%>
  </div>
  <div class="text d-flex justify-content-center align-items-center">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum, ratione! Quos asperiores, numquam dolorum. Libero harum officiis velit alias ut dicta molestias asperiores sapiente, minima expedita quis, exercitationem mollitia quo sed. Sint, harum doloribus, earum porro nihil pariatur veniam eum nobis nemo corporis repudiandae. Harum, eveniet eos quia totam inventore esse minima veniam, fugit earum repellendus consequuntur beatae ullam architecto quis id dolor itaque. Earum ea voluptate a suscipit officiis non reprehenderit excepturi quia labore modi, deserunt aliquam, iusto magnam. Eius quam at sed, soluta, rerum praesentium, dignissimos aspernatur animi necessitatibus neque magni dolores vero. Nihil officiis fugit quod error.</p>
  </div>
</div>
<div class="container">
    <div class="text d-flex justify-content-center align-items-center">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum, ratione! Quos asperiores, numquam dolorum. Libero harum officiis velit alias ut dicta molestias asperiores sapiente, minima expedita quis, exercitationem mollitia quo sed. Sint, harum doloribus, earum porro nihil pariatur veniam eum nobis nemo corporis repudiandae. Harum, eveniet eos quia totam inventore esse minima veniam, fugit earum repellendus consequuntur beatae ullam architecto quis id dolor itaque. Earum ea voluptate a suscipit officiis non reprehenderit excepturi quia labore modi, deserunt aliquam, iusto magnam. Eius quam at sed, soluta, rerum praesentium, dignissimos aspernatur animi necessitatibus neque magni dolores vero. Nihil officiis fugit quod error.</p>
  </div>
  <div class="photo d-flex justify-content-center align-items-center">
    <%= image_tag("Fanny.jpeg", size: "200x200", class: "rounded-circle")%>
  </div>

</div>

app/views/pages/contact.html.erb
<div class="banner2" w-100 >
  <%= cl_image_tag "whitelamps_rjsyhi", class: "bannerpicture" %>
</div>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar_home") %>


<div class="banner">
  <div class="container">
    <div class="banner-content d-flex flex-column">
      <h1>Design d'Intérieur</h1>
      <p>Agencement & Décoration</p>
    </div>
  </div>
</div>







<!-- <div class="banner">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Design d'Intérieur</h1>
      </div>
    <div class="row">
      <p>Agencement & Décoration</p>
    </div>
    </div>
  </div>
</div>


 -->

app/views/pages/prestations.html.erb
<div class="banner2" w-100 >
  <%= cl_image_tag 'pierre-chatel-lamp2_ijcoep', crop: :fill, class: "bannerpicture" %>

</div>

app/views/realisations/_form.html.erb
  <%= simple_form_for(@realisation) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if
    f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/realisations/create.html.erb
<h1>Realisations#create</h1>
<p>Find me in app/views/realisations/create.html.erb</p>

app/views/realisations/destroy.html.erb
<h1>Realisations#destroy</h1>
<p>Find me in app/views/realisations/destroy.html.erb</p>

app/views/realisations/edit.html.erb
<h1>Realisations#edit</h1>
<p>Find me in app/views/realisations/edit.html.erb</p>

<div class="container">
  <%= render 'form' %>
</div>

app/views/realisations/index.html.erb
<div class="banner2" w-100 >
  <%= image_tag "greenlamp3.jpg", class: "bannerpicture" %>
</div>

<div class="container d-flex justify-content-center">
  <div class="intro text-center">
    <p>Vous trouverez ci-dessous une sélection de projets <br>
    sur lesquels j'ai eu le plaisir de travailler</p>
  </div>

  <div class="cards-realisations text-center">
    <% @realisations.each do |realisation| %>
      <%= link_to realisation_path(realisation) do %>
      <div id="parent" class="card-realisation">
      <div class= "card-name"><%= realisation.name %></div>
    </div>
    <% end %>
    <% end %>
  </div>


</div>

 <%= link_to 'Créer une nouvelle réalisation', new_realisation_path %>

app/views/realisations/new.html.erb
<h1>Realisations#new</h1>
<p>Find me in app/views/realisations/new.html.erb</p>

<div class="container">
  <%= render 'form' %>
</div>

app/views/realisations/show.html.erb
<h1><%= @realisation.name %></h1>
<h4><%= @realisation.category %></h4>
<% @realisation.photos.each  do |photo| %>
<%= cl_image_tag photo.key, width: 100, height: 100, crop: :fill %>
<% end %>

<%= cl_image_tag @realisation.photos[1].key, width: 100, height: 100, crop: :fill %>

<%= link_to 'Retour à la liste', realisations_path %>
<%= link_to 'Modifier', edit_realisation_path(@realisation) %>
<%= link_to 'Supprimer', realisation_path(@realisation), method: :delete, data: { confirm: 'Es-tu bien sure de toi ma puff?'} %>

app/views/realisations/update.html.erb
<h1>Realisations#update</h1>
<p>Find me in app/views/realisations/update.html.erb</p>

app/views/shared/_footer.html.erb
  <div class="footer-cards">
    <div class="card-copyright d-flex justify-content-center align-items-center">
      ©2020. Fanny Castillon | Bordeaux.
    </div>
    <div class="card-media-links d-flex justify-content-center align-items-center">
      <a href="https://www.instagram.com/fanny_castillon_decoration" target="_blank"><i class="fab fa-instagram "></i></a>
      <a href="#"><i class="fab fa-facebook pl-4"></i></a>
      <a href="#"><i class="fab fa-linkedin pl-4"></i></a>
    </div>
  </div>
<!--

  <div class="cards">
    <div class="card d-flex justify-content-center align-items-center">
      ©2020. Fanny Castillon. Tous droits réservés.
    </div>
    <div class="card d-flex justify-content-center align-items-center">
      <div class="media-links">
        <a href="https://www.instagram.com/Fanny_Deco" target:"_blank"><i class="fab fa-instagram "></i></a>
        <a href="#"><i class="fab fa-facebook pl-4"></i></a>
        <a href="#"><i class="fab fa-linkedin pl-4"></i></a>
      </div>
    </div>
  </div>


 -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar_home ">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end pt-3 pr-5" id="navbarSupportedContent">
    <ul class="navbar-nav ">
      <li class="nav-item active">
        <%= link_to "HOME", "home", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "BIO", "bio", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "REALISATIONS", "realisations", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "PRESTATIONS", "prestations", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "BLOG", "blog", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "CONTACT", "contact", class: "nav-link" %>
      </li>
    </ul>
  </div>


</div>